### 授权码模式
### 第一步申请授权码(浏览器请求)/oauth/authorize?client_id=c1&response_type=code&scope=all&redirect_uri=http://www.51xuecheng.cn
### 第二步申请令牌
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=CTvCrB&redirect_uri=http://www.51xuecheng.cn


### 密码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=zhangsan&password=123

################扩展认证请求参数后######################
###密码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username={"username":"stu1","authType":"password","password":"111111"}

###校验jwt令牌
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjcmVhdGVUaW1lXCI6XCIyMDI0LTA5LTI3VDEzOjM4OjE5XCIsXCJpZFwiOlwiODUyMTAzMWEtYTFhMi00MWU0LWI2YjQtMGU2NzMzODdkM2VkXCIsXCJuYW1lXCI6XCJDY2NcIixcIm5pY2tuYW1lXCI6XCJDY2NcIixcInBlcm1pc3Npb25zXCI6W10sXCJzdGF0dXNcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJvV2dHejFCM29pVHlaY0ZZRE9OZm5EdDRuUy1NXCIsXCJ1dHlwZVwiOlwiMTAxMDAxXCIsXCJ3eFVuaW9uaWRcIjpcIm9XZ0d6MUIzb2lUeVpjRllET05mbkR0NG5TLU1cIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNzI4MDMzNDk4LCJhdXRob3JpdGllcyI6WyJ4Y19zeXNtYW5hZ2VyX2RvYyIsInhjX3RlYWNobWFuYWdlcl9jb3Vyc2VfbGlzdCIsInhjX3N5c21hbmFnZXIiLCJ4Y19zeXNtYW5hZ2VyX2NvbXBhbnkiLCJ4Y19zeXNtYW5hZ2VyX2xvZyJdLCJqdGkiOiJjZDIzMDI2ZC0zOTM0LTRhZmEtYWVlNi1lMTBkNjg3MTU3ZWEiLCJjbGllbnRfaWQiOiJYY1dlYkFwcCJ9.jld7GV2t_O10v4VB4ZYtMd59nM9Sdzrb6xqzb3jq3co